spring:
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 300
#    password:
#    pool:
#      max-active: 10
#      max-wait: 300
#      min-idle: 1
#      max-idle: 10
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.127.45:3306/hospital?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: medicalsystem
    password: medicalsystem

#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  port: 8080
  servlet:
    context-path: /

  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

